apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: '{{ .Release.Namespace }}'

resources:
- input/vsphere-csi-driver.yaml
patches:
- path: patches/daemonset-csi-node-driver-registrar-initcontainer.yaml
- path: patches/deployment-images.yaml
- path: patches/internal-feature-states-topology.yaml
