# Allow csi-vcd-controllerplugin to access world (vsphere api)
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: csi-allow-egress
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: vsphere-csi-controller
  egress:
  - {}
  policyTypes:
  - Egress
