apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: vsphere-csi-node-binding
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vsphere-csi-node-role
subjects:
- kind: ServiceAccount
  name: vsphere-csi-node
  namespace: '{{ .Release.Namespace }}'
