apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: vsphere-csi-node-cluster-role
rules:
- apiGroups:
  - cns.vmware.com
  resources:
  - csinodetopologies
  verbs:
  - create
  - watch
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
