apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    app: vsphere-csi-controller
  name: vsphere-csi-controller
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: ctlr
    port: 2112
    protocol: TCP
    targetPort: 2112
  - name: syncer
    port: 2113
    protocol: TCP
    targetPort: 2113
  selector:
    app: vsphere-csi-controller
