{{- $config := .Values.config -}}
{{- if .Values.global -}}
{{- if .Values.global.config -}}
{{- $config = mergeOverwrite (deepCopy .Values.config) .Values.global.config -}}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData: 
  csi-vsphere.conf: |
    [Global]
    cluster-id = "{{ $config.clusterId }}"

    {{- if $config.thumbprint }}
    thumbprint = {{ $config.thumbprint | quote }}
    {{- end }}
    

    [VirtualCenter "{{ $config.vcenter }}"]
    {{- if not $config.thumbprint }}
    insecure-flag = "true"
    {{- end }}
    
    user = "{{ $config.username }}"
    password = "{{ $config.password }}"
    port = "443"
    datacenters = "{{ $config.datacenter }}"
