apiVersion: v1
data:
  topology-preferential-datastores: "{{ .Values.internalFeatureStates.topologyPreferentialDatastores.enabled }}"
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: vmware-system-csi
