{{- if .Values.clusterRoleBinding.enabled -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-role-binding
  namespace: {{ include "resource.default.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: "{{ include "resource.default.name" . }}-role"
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
