{{- if .Values.csidriver.enabled -}}
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: csi.vsphere.vmware.com
spec:
  attachRequired: true
  podInfoOnMount: false
{{- end -}}
